# Generated by Django 5.2.7 on 2025-10-30 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0005_tag_birthday_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
